"""Base class for tasks that run after experiments complete."""

from abc import ABC, abstractmethod
from typing import Any


class Task(ABC):
    """Base class for analysis tasks that run after experiments.

    Tasks can depend on experiments and are automatically run
    after their dependencies complete. They can also be invoked manually.
    """

    # Registry of all tasks
    tasks: dict[str, type["Task"]] = {}

    def __init_subclass__(cls, **kwargs):
        """Automatically register tasks."""
        super().__init_subclass__(**kwargs)
        if hasattr(cls, "name"):
            Task.tasks[cls.name] = cls

    # Name of this task (should be set by subclasses)
    name: str

    # Experiments this task follows (should be set by subclasses)
    follows: list[str] = []

    @staticmethod
    @abstractmethod
    def get_schema_sql() -> str:
        """Return SQL to create database tables for this task.

        Returns:
            SQL string to create necessary tables and indices.
        """

    @staticmethod
    @abstractmethod
    def run(db: Any) -> dict[str, Any]:
        """Run the task.

        Args:
            db: Database connection object.

        Returns:
            Dictionary with results/statistics from the task.
        """

    @staticmethod
    @abstractmethod
    def store_to_database(db: Any, data: dict[str, Any]):
        """Store task results to database.

        Args:
            db: Database connection object.
            data: Results from run() to store.
        """

    @staticmethod
    @abstractmethod
    def delete_data(db: Any):
        """Delete all data generated by this task.

        Args:
            db: Database connection object.
        """
