# repository deduplication via minhash.
#
# We use line-level shingles. word-level is too coarse because all repos share common
# keywords like "def", "class", etc. We normalize by stripping whitespace.
# (A "shingle" is an overlapping sliding window, though in the case of 1 line per
# shingle there is no overlap.)
#
# Each .py file in a repo gets a minhash. We compute the number of duplicate files
# between two repos by looking at bruteforce pairwise-combinations of the minhash
# jaccard similarity, at a given threshold level.

import multiprocessing
import pickle
import random
import re
import subprocess
import tempfile
from multiprocessing import Pool
from pathlib import Path

from datasketch import MinHash

from .utils import Reject

num_perm = 128
# skip hashing files with fewer lines than this
min_file_lines = 25
# maximum number of files to hash per repository (randomly sampled)
max_files_per_repo = 500

# if both:
#
# * x% of files from repo1 are duplicated in repo2
# * x% of files from repo2 are duplicated in repo1
#
# then count it as a dupliate. We keep the one with a higher star count.
overlap_threshold = 0.3
# required minhash jaccard similarity for two files to be considered duplicates
jaccard_threshold = 0.75

# generated by claude, but seems reasonable enough
EXCLUDE_DIRS = {
    # Version control
    ".git",
    # Package managers and dependencies
    "node_modules",
    "venv",
    "env",
    ".venv",
    ".env",
    "virtualenv",
    "site-packages",
    "vendor",
    # Third-party/external code
    "third_party",
    "thirdparty",
    "external",
    "lib",
    "libs",
    # Python artifacts
    "__pycache__",
    ".eggs",
    ".egg-info",
    # Testing and coverage
    ".tox",
    ".nox",
    ".pytest_cache",
    ".mypy_cache",
    ".hypothesis",
    "htmlcov",
    ".coverage",
    # Build artifacts
    "build",
    "dist",
    # other
    ".vscode",
}

# eg a directory like numpy-1.19.5-py3.6-linux-x86_64.egg
EXCLUDE_DIR_ENDINGS = {".egg"}


def _is_vendored_directory(name: str) -> bool:
    """Check if directory name looks like vendored code (e.g., has commit hash)."""
    # Check for commit hash pattern (40 hex chars) in directory name
    # e.g., fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1
    return bool(re.search(r"-[0-9a-f]{40}$", name))


def _reasonable_paths(path: Path) -> list[Path]:
    python_files = []

    for item in path.iterdir():
        if item.name in EXCLUDE_DIRS:
            continue
        if item.is_dir() and any(item.name.endswith(v) for v in EXCLUDE_DIR_ENDINGS):
            continue

        # bad/silly symlinks can cause infinite loops. skip them
        if item.is_symlink():
            continue
        if item.is_dir() and _is_vendored_directory(item.name):
            continue

        if item.is_dir():
            python_files += _reasonable_paths(item)
        elif item.is_file():
            python_files.append(item)
    return python_files


def _repo_exists(repo_name: str) -> bool:
    return (
        subprocess.run(
            ["git", "ls-remote", f"https://github.com/{repo_name}.git"],
            capture_output=True,
            timeout=10,
        ).returncode
        == 0
    )


def _valid_repo(clone_path: Path) -> bool:
    reasonable_paths = _reasonable_paths(clone_path)

    if not (
        any(p.name == "pytest.ini" for p in reasonable_paths)
        or any(p.name == "conftest.py" for p in reasonable_paths)
        or any(
            p.name.startswith("test_") and p.suffix == ".py" for p in reasonable_paths
        )
    ):
        return False

    common_packages = {"pip", "requests", "numpy", "setuptools"}
    for sitepackages_p in clone_path.rglob("site-packages"):
        if sitepackages_p.is_dir():
            dirnames = {p.name for p in sitepackages_p.iterdir() if p.is_dir()}
            if dirnames & common_packages:
                return False

    return True


def compute_minhashes(repo_name: str) -> list[MinHash]:
    assert "/" in repo_name

    # vscode asks me to sign into git if we try to clone a repo that doesnt
    # exist. early-error here
    if not _repo_exists(repo_name):
        raise ValueError(f"Repository {repo_name} not found or not accessible")

    minhashes = []
    with tempfile.TemporaryDirectory() as tmpdir:
        clone_path = Path(tmpdir) / "repo"
        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                f"https://github.com/{repo_name}.git",
                str(clone_path),
            ],
            check=True,
        )

        if not _valid_repo(clone_path):
            raise Reject("invalid_repo")

        python_files = []
        reasonable_paths = [
            p for p in _reasonable_paths(clone_path) if p.suffix == ".py"
        ]
        for p in reasonable_paths:
            try:
                content = p.read_text(encoding="utf-8", errors="ignore")
                lines = content.splitlines()
                if len(lines) >= min_file_lines:
                    python_files.append(lines)
            except Exception:
                continue

        if len(python_files) > max_files_per_repo:
            python_files = random.sample(python_files, max_files_per_repo)

        for lines in python_files:
            m = MinHash(num_perm=num_perm)
            for line in lines:
                normalized = line.strip()
                # normalize whitespace. skip empty lines.
                if normalized:
                    m.update(normalized.encode("utf-8"))
            minhashes.append(m)

    return minhashes


def load_minhashes(db, repo_name: str) -> list[MinHash] | None:
    result = db.fetchone(
        "SELECT id FROM core_repository WHERE full_name = ?",
        (repo_name,),
    )
    assert result

    repo_id = result["id"]
    rows = db.fetchall(
        "SELECT minhash_data FROM core_minhashes WHERE repo_id = ?",
        (repo_id,),
    )
    return [pickle.loads(row["minhash_data"]) for row in rows]


def minhash_repository(db, repo_name: str):
    minhashes = compute_minhashes(repo_name)

    result = db.fetchone(
        "SELECT id FROM core_repository WHERE full_name = ?",
        (repo_name,),
    )
    assert result
    repo_id = result["id"]

    db.execute("DELETE FROM core_minhashes WHERE repo_id = ?", (repo_id,))
    for minhash in minhashes:
        minhash_blob = pickle.dumps(minhash)
        db.execute(
            "INSERT INTO core_minhashes (repo_id, minhash_data) VALUES (?, ?)",
            (repo_id, minhash_blob),
        )

    db.commit()


def _is_subset(
    hashes1: list[MinHash],
    hashes2: list[MinHash],
    *,
    jaccard_threshold: float,
    overlap_threshold: float,
) -> tuple[bool, float | None]:
    # we need this many files to match in order to return True.
    # So for example if we had 10 hashes in hashes1, and overlap_threshold=0.3 -
    # meaning that 30% of the files must match - then threshold_count = 3, and
    # we'll stop as soon as it's not possible to get to that threshold.
    threshold_count = overlap_threshold * len(hashes1)
    count = 0

    for i, hash1 in enumerate(hashes1):
        for hash2 in hashes2:
            similarity = hash1.jaccard(hash2)
            if similarity >= jaccard_threshold:
                count += 1
                # maximum one match per file
                break

        # check if it's still possible to reach the required threshold, assuming
        # all of the remaining files are duplicates.
        remaining = len(hashes1) - (i + 1)
        if count + remaining < threshold_count:
            return (False, None)

    overlap_percentage = count / len(hashes1)
    is_subset = overlap_percentage >= overlap_threshold
    return (is_subset, overlap_percentage)


def _compare_two_repos(args):
    repo1, repo2, hashes1, hashes2 = args

    is_subset1, overlap1 = _is_subset(
        hashes1,
        hashes2,
        jaccard_threshold=jaccard_threshold,
        overlap_threshold=overlap_threshold,
    )
    if not is_subset1:
        return (repo1, repo2, False, None, None)

    is_subset2, overlap2 = _is_subset(
        hashes2,
        hashes1,
        jaccard_threshold=jaccard_threshold,
        overlap_threshold=overlap_threshold,
    )

    is_duplicate = is_subset2
    return (repo1, repo2, is_duplicate, overlap1, overlap2)


def filter_duplicates(db, *, num_workers=None):
    if num_workers is None:
        num_workers = multiprocessing.cpu_count()
    all_repos = db.fetchall(
        "SELECT id, full_name, stargazers_count FROM core_repository WHERE status IS NULL"
    )
    print(f"Removing duplicates among {len(all_repos)} repositories...")

    # note: this loads all minhashes into memory. you might OOM. my minhash size
    # was 3gb, which was manageable.
    print(f"Loading minhashes for {len(all_repos)} repositories...")
    all_minhashes = {}
    repos = []
    for repo in all_repos:
        repo = dict(repo)
        hashes = load_minhashes(db, repo["full_name"])
        # skip repos with zero minhashes
        if not hashes:
            continue
        all_minhashes[repo["full_name"]] = hashes
        repos.append(repo)
    print(f"Loaded {len(repos)} repos with minhashes (among {len(repos)} repositories)")

    to_remove = set()
    with Pool(num_workers) as pool:
        for i, repo1 in enumerate(repos):
            print(f"[{i}/{len(repos)}] {repo1['full_name']} ... ", flush=True)

            repo1_name = repo1["full_name"]
            if repo1_name in to_remove:
                continue

            hashes1 = all_minhashes[repo1_name]

            comparisons = []
            for repo2 in repos[i + 1 :]:
                repo2_name = repo2["full_name"]
                if repo2_name in to_remove:
                    continue

                hashes2 = all_minhashes[repo2_name]
                comparisons.append((repo1, repo2, hashes1, hashes2))

            if comparisons:
                for result in pool.imap_unordered(_compare_two_repos, comparisons):
                    repo1, repo2, is_duplicate, overlap1, overlap2 = result

                    if not is_duplicate:
                        continue

                    repo1_name = repo1["full_name"]
                    repo2_name = repo2["full_name"]

                    # Keep the one with more stars, remove the other
                    if repo1["stargazers_count"] >= repo2["stargazers_count"]:
                        repo_to_remove = repo2_name
                        repo_to_keep = repo1_name
                    else:
                        repo_to_remove = repo1_name
                        repo_to_keep = repo2_name

                    print(
                        f"  Duplicate: {repo1_name} ↔ {repo2_name} "
                        f"({overlap1:.1%}/{overlap2:.1%}) - removing {repo_to_remove}"
                    )

                    to_remove.add(repo_to_remove)
                    status_reason = f"minhash_duplicate ({repo_to_keep}, {overlap1:.1%}/{overlap2:.1%})"
                    db.execute(
                        "UPDATE core_repository SET status = ?, status_reason = ? WHERE full_name = ?",
                        ("invalid", status_reason, repo_to_remove),
                    )
                    db.commit()

                    if repo_to_remove == repo1_name:
                        break  # This repo is being removed, move to next

    print(f"\nMarked {len(to_remove)} duplicate repositories")
    print(f"Kept {len(repos) - len(to_remove)} unique repositories")
