# repository deduplication via minhash.
#
# We use line-level shingles. word-level is too coarse because all repos share common
# keywords like "def", "class", etc. We normalize by stripping whitespace.
# (A "shingle" is an overlapping sliding window, though in the case of 1 line per
# shingle there is no overlap.)
#
# Each .py file in a repo gets a minhash. We compute the number of duplicate files
# between two repos by looking at bruteforce pairwise-combinations of the minhash
# jaccard similarity, at a given threshold level.

import pickle
import random
import re
import subprocess
import tempfile
from pathlib import Path

from datasketch import MinHash

from .utils import Reject

num_perm = 128
# skip hashing files with fewer lines than this
min_file_lines = 25
# maximum number of files to hash per repository (randomly sampled)
max_files_per_repo = 500

# if both:
#
# * x% of files from repo1 are duplicated in repo2
# * x% of files from repo2 are duplicated in repo1
#
# then count it as a dupliate. We keep the one with a higher star count.
overlap_threshold = 0.3
# required minhash jaccard similarity for two files to be considered duplicates
jaccard_threshold = 0.75

# generated by claude, but seems reasonable enough
EXCLUDE_DIRS = {
    # Version control
    ".git",
    # Package managers and dependencies
    "node_modules",
    "venv",
    "env",
    ".venv",
    ".env",
    "virtualenv",
    "site-packages",
    "vendor",
    # Third-party/external code
    "third_party",
    "thirdparty",
    "external",
    "lib",
    "libs",
    # Python artifacts
    "__pycache__",
    ".eggs",
    ".egg-info",
    # Testing and coverage
    ".tox",
    ".nox",
    ".pytest_cache",
    ".mypy_cache",
    ".hypothesis",
    "htmlcov",
    ".coverage",
    # Build artifacts
    "build",
    "dist",
    # other
    ".vscode",
}


def _is_vendored_directory(name: str) -> bool:
    """Check if directory name looks like vendored code (e.g., has commit hash)."""
    # Check for commit hash pattern (40 hex chars) in directory name
    # e.g., fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1
    return bool(re.search(r"-[0-9a-f]{40}$", name))


def _reasonable_paths(path: Path) -> list[Path]:
    python_files = []

    for item in path.iterdir():
        if item.name in EXCLUDE_DIRS:
            continue
        # bad/silly symlinks can cause infinite loops. skip them
        if item.is_symlink():
            continue
        if item.is_dir() and _is_vendored_directory(item.name):
            continue

        if item.is_dir():
            python_files += _reasonable_paths(item)
        elif item.is_file():
            python_files.append(item)
    return python_files


def _repo_exists(repo_name: str) -> bool:
    return (
        subprocess.run(
            ["git", "ls-remote", f"https://github.com/{repo_name}.git"],
            capture_output=True,
            timeout=10,
        ).returncode
        == 0
    )


def _valid_repo(clone_path: Path) -> bool:
    reasonable_paths = _reasonable_paths(clone_path)

    if not (
        any(p.name == "pytest.init" for p in reasonable_paths)
        or any(p.name == "conftest.py" for p in reasonable_paths)
        or any(
            p.name.startswith("test_") and p.suffix == ".py" for p in reasonable_paths
        )
    ):
        return False

    common_packages = {"pip", "requests", "numpy", "setuptools"}
    for sitepackages_p in clone_path.rglob("site-packages"):
        if sitepackages_p.is_dir():
            dirnames = {p.name for p in sitepackages_p.iterdir() if p.is_dir()}
            if dirnames & common_packages:
                return False

    return True


def compute_minhashes(repo_name: str) -> list[MinHash]:
    assert "/" in repo_name

    # vscode asks me to sign into git if we try to clone a repo that doesnt
    # exist. early-error here
    if not _repo_exists(repo_name):
        raise ValueError(f"Repository {repo_name} not found or not accessible")

    minhashes = []
    with tempfile.TemporaryDirectory() as tmpdir:
        clone_path = Path(tmpdir) / "repo"
        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "--quiet",
                f"https://github.com/{repo_name}.git",
                str(clone_path),
            ],
            check=True,
        )

        if not _valid_repo(clone_path):
            raise Reject("invalid_repo")

        python_files = []
        reasonable_paths = [
            p for p in _reasonable_paths(clone_path) if p.suffix == ".py"
        ]
        for p in reasonable_paths:
            try:
                content = p.read_text(encoding="utf-8", errors="ignore")
                lines = content.splitlines()
                if len(lines) >= min_file_lines:
                    python_files.append(lines)
            except Exception:
                continue

        if len(python_files) > max_files_per_repo:
            python_files = random.sample(python_files, max_files_per_repo)

        for lines in python_files:
            m = MinHash(num_perm=num_perm)
            for line in lines:
                normalized = line.strip()
                # normalize whitespace. skip empty lines.
                if normalized:
                    m.update(normalized.encode("utf-8"))
            minhashes.append(m)

    return minhashes


def load_minhashes(db, repo_name: str) -> list[MinHash] | None:
    result = db.fetchone(
        "SELECT id FROM core_repository WHERE full_name = ?",
        (repo_name,),
    )
    assert result

    repo_id = result["id"]
    rows = db.fetchall(
        "SELECT minhash_data FROM core_minhashes WHERE repo_id = ?",
        (repo_id,),
    )
    return [pickle.loads(row["minhash_data"]) for row in rows]


def minhash_repository(db, repo_name: str):
    minhashes = compute_minhashes(repo_name)

    result = db.fetchone(
        "SELECT id FROM core_repository WHERE full_name = ?",
        (repo_name,),
    )
    assert result
    repo_id = result["id"]

    db.execute("DELETE FROM core_minhashes WHERE repo_id = ?", (repo_id,))
    for minhash in minhashes:
        minhash_blob = pickle.dumps(minhash)
        db.execute(
            "INSERT INTO core_minhashes (repo_id, minhash_data) VALUES (?, ?)",
            (repo_id, minhash_blob),
        )

    db.commit()


def _is_subset(
    hashes1: list[MinHash],
    hashes2: list[MinHash],
    *,
    jaccard_threshold: float,
    overlap_threshold: float,
) -> bool:
    count = 0
    for hash1 in hashes1:
        for hash2 in hashes2:
            similarity = hash1.jaccard(hash2)
            if similarity >= jaccard_threshold:
                count += 1
                # maximum one match per file
                break

    overlap_percentage = count / len(hashes1)
    return overlap_percentage >= overlap_threshold


def filter_duplicates(db):
    repos = db.fetchall(
        "SELECT id, full_name, stargazers_count FROM core_repository WHERE status IS NULL"
    )
    print(f"Removing duplicates among {len(repos)} repositories...")

    # note: this loads all minhashes into memory. you might OOM. my minhash size
    # was 3gb, which was manageable.
    print(f"Loaded minhashes for {len(repos)} repositories...")
    all_minhashes = {}
    for repo in repos:
        all_minhashes[repo["full_name"]] = load_minhashes(db, repo["full_name"])
    print(f"Loaded minhashes for {len(repos)} repositories")

    to_remove = set()
    for i, repo1 in enumerate(repos):
        print(f"[{i}/{len(repos)}] {repo1['full_name']} ... ", flush=True)
        if repo1["full_name"] in to_remove:
            continue

        repo1_name = repo1["full_name"]
        hashes1 = all_minhashes[repo1_name]
        if not hashes1:
            continue

        for repo2 in repos[i + 1 :]:
            if repo2["full_name"] in to_remove:
                continue

            repo2_name = repo2["full_name"]
            hashes2 = all_minhashes[repo2_name]
            if not hashes2:
                continue

            overlap1 = _is_subset(
                hashes1,
                hashes2,
                jaccard_threshold=jaccard_threshold,
                overlap_threshold=overlap_threshold,
            )
            # we require both to be over the threshold. For efficiency, don't compute
            # the other direction if the first fails
            if not overlap1:
                continue
            overlap2 = _is_subset(
                hashes2,
                hashes1,
                jaccard_threshold=jaccard_threshold,
                overlap_threshold=overlap_threshold,
            )
            if overlap2:
                print(
                    f"  Duplicate: {repo1_name} ↔ {repo2_name} ({overlap1:.1%}/{overlap2:.1%})"
                )
                # Keep the one with more stars, remove the other
                stars1 = repo1["stargazers_count"]
                stars2 = repo2["stargazers_count"]
                if stars1 >= stars2:
                    to_remove.add(repo2_name)
                else:
                    to_remove.add(repo1_name)
                    break  # This repo is being removed, move to next

    print(f"\nMarking {len(to_remove)} duplicate repositories...")
    for repo_name in to_remove:
        db.execute(
            "UPDATE core_repository SET status = ?, status_reason = ? WHERE full_name = ?",
            ("invalid", "minhash_duplicate", repo_name),
        )
    db.commit()
    print(f"Kept {len(repos) - len(to_remove)} unique repositories")
